import type { Metadata } from "next";
import {
  Amatic_SC,
  Geist_Mono,
  Caveat,
  Permanent_Marker,
} from "next/font/google";
import "./globals.css";

// Specify the available weights for Permanent Marker
const permanentMarker = Permanent_Marker({
  weight: "400",
  variable: "--font-permanent-marker",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` background ${permanentMarker.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
